### ISSUE TITLE
Implement server redux store

### ISSUE THREAD

**Issue by corourke** [corourke/nodewarz-server#1]
@corourke commented on [Sat Jun 10 2017](https://github.com/corourke/nodewarz-client/issues/6)

users, games, network map

**Comment by corourke** [comment]
Need to remove game object

**Comment by corourke** [comment]
Yeah, so this isn't really done. The SERVER store needs to track multiple games, and the users assigned to those games along with the game state of each game.

**Comment by Z-vop** [comment]
Closing this and making a new issue.
